services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  transcoding-service:
    build: .
    ports:
      - "3006:3006"
      - "3001:3001"
    environment:
      NODE_ENV: production
      KAFKA_HOST: kafka:9092
      KAFKA_TRANSCODE_TOPIC: transcode-requests
      INPUT_VIDEO_PATH: /app/videos/input
      OUTPUT_VIDEO_PATH: /app/videos/output
      HEALTH_CHECK_PORT: 3001
    volumes:
      - ./videos/input:/app/videos/input
      - ./videos/output:/app/videos/output
    depends_on:
      - kafka